### ISSUE TITLE
Element hiding rules overruled by inline styles with !important modifier

### ISSUE THREAD

**Issue by Ext3h** [gorhill/uBlock#1031]
Taking http://www.extremetech.com/ as an example, it contains `<div class="" style="display: inherit ! important;" id="jivvmzil">`.

The inlined CSS overrides the rule `extremetech.com###jivvmzil`, meaning the element remains visible despite  being matched by the rule.

The expected behavior would be that the element hiding rules precede any inline style, including when it uses the `! impotant` modifier.

Tested with uBlock Origin 1.3.6 on Firefox.

One possible solution would be, to forcefully apply all matched element hiding rules to the DOM, stripping all matched elements from possible inline CSS.

**Comment by Halibut80** [comment]
Fixed in beta (<a href="https://github.com/gorhill/uBlock/issues/1011">https://github.com/gorhill/uBlock/issues/1011</a>)

**Comment by gorhill** [comment]
Not fixed by #1011. It's different here, inlined CSS rules always win over CSS rules from within style tags. #1011 was about two CSS rules within each their own style tags, and uBO losing the CSS rule specificity "battle".

However, this is a duplicate of #963.

**Comment by harshanvn** [comment]
this particualr site was nasty to me yesterday. it was behaving very weirdly -
i.e., -
   - it reloads automatically after 2-3 minutes, and never finishes
             (if the site is opened in a new tab, it is opened however)
   - the top banner (bannerAd) is not closed (there is some inline script code to do that), how ever due gpt.js redirect i believe it is not happening..

Anyways, i was able nullify all the side effects with few <b>inline script tag</b> filters. I will share them later i reach home, so anyone need can use them..

Tested with v1.4rc0 (experimental filters enabled + medium blocking mode) - FF v42 64 bit

**Comment by gorhill** [comment]
Never mind all what I said above, I was commenting based on presumption of what the site was doing. There is something else going on here. I see the site is using shadow DOM, this is probably where the issue is. Investigating.

**Comment by gorhill** [comment]
I get it, the web page is disabling uBO's own style tag using [`stylesheet.disabled` property](https://developer.mozilla.org/en-US/docs/Web/API/StyleSheet/disabled). So uBO will have to be ready to deal with this kind of behavior.

**Comment by gorhill** [comment]
The code change for the fix is rather minimal:

There was already code in there to test whether our injected style tags had been removed, the added code essentially is just one more test, to see if `style.disabled` is `true`, and if so the style tag will be re-inserted after setting `disabled` to `false`.

The fix works well for both Chromium/Firefox, though for Firefox there is a small residual DOM element left behind, but I expect this will be gone once #963 is fixed.

**Comment by gorhill** [comment]
Change title to reflect more accurately the issue which was fixed.

**Comment by PekaFat** [comment]
It's still not fixed (https://github.com/gorhill/uBlock/issues/1011).

**Comment by gorhill** [comment]
Works fine here, be sure your filter lists are up to date. There is a bit of visual glitch but that is the site trying so hard to work around blockers by shuffling things around in the DOM -- but the ads are blocked.

**Comment by PekaFat** [comment]
> I don't understand your comment, you say it does not work on your side with Chrome 47, and you solve it by using Firefox-only CSS rules?

uBlock does not block banner on https://e.mail.ru/messages/inbox/, but with css-fixes in Stylish extension banner is blocked.

I block this banner manually in uBlock, but after refresh page - banner shows again.

**Comment by gorhill** [comment]
Why report this issue here? The issue here is fixed and is unrelated to #1011.

**Comment by PekaFat** [comment]
It's not fixed, just try it on https://e.mail.ru/messages/inbox/ by yourself.

**Comment by Morisatos** [comment]
Hey gorhill. Loving your extension keep up the great work. I know this is an old issue and has been deemed fixed but I still have some issues with this site on current v1.6.4b0 of ublock0.

-Filters up to date
-ublock0 up to date
-Filters DO block ads from appearing but the frames/styles (whatever it's called) still remain with greyed out boxes of where the ads should be.

How do I go about blocking or hiding these if at all? Every refresh it loads the following:

javascript:"<html><body%20style='background:transparent'></body></html>"$domain=www.extremetech.com

www.extremetech.com###jivvmzil (this always leaves a tiny bar behind followed by the one below)
www.extremetech.com###jivvmzil > .(random letters upon refresh)
www.extremetech.com###BwxJivvmz
www.extremetech.com###owwotm_ila_qnzium_\/4585\/zd\.extech\/_ATF_0
www.extremetech.com###owwotm_ila_qnzium_\/4585\/zd\.extech\/_ATF_0__container__
