### ISSUE TITLE
Blocking inline scripts inside iframe

### ISSUE THREAD

**Issue by olloff** [gorhill/uBlock#1201]
Hi, I feel I need help from community again.
uBlock 1.5.3, FF Nightly, if that matters.

How _script:contains()_ works with iframes? Let's suppose we have a page with iframe site2.com on page site1.com.

    <head>
        <script>popup1()</script>
    </head>
    <body>
        <iframe src='site2.com'>
            <head>
                <script>popup2()</script>
            </head>
        </iframe>
    </body>

Normally I do _site1.com##script:contains(/popup1/)_ and it just works. But can I block popup2() with _site1.com##script:contains(/popup2/)_?

So my problem is related to openload.co
Popups within this iframe: https://openload.co/embed/FDbkZ5f8Uv4 (*NSFW warning!*) are blocked with next rule:

    openload.co##script:contains(/.*?popAdsLoaded.*?/)

But within page http://javhub.net/play/d122f1105/55c458aa6fb5fc4e25a6ad74/JUX-626-F-of-beauty-milf-play-with-temptation-younger-man-boss-Dirty-cum-Chaoyang-Mizuno  (*NSFW warning!*) popups are still present and next filter is not working as 
    
    javhub.net/##script:contains(/.*?popAdsLoaded.*?/)

P.S. I love you @gorhill in a way man can love his fav software developer. Inline script blocking was definitely the best news of 2015.

**Comment by gorhill** [comment]
> javhub.net/##script:contains(/.*?popAdsLoaded.*?/)

Inline script tag filters fall in the "cosmetic filters" category. This means the syntax of cosmetic filtering must be respected. When prepending a cosmetic filter with the domain name(s) on which it must act, the domain name(s) have to be plain hostnames separated by commas (`,`). In your filter above, the syntax is not respected, you added trailing `/` to `javhub.net`. Try:

> javhub.net##script:contains(/.*?popAdsLoaded.*?/)

**Comment by olloff** [comment]
Sorry, that's my fault, I do use filter as you suggested

    javhub.net##script:contains(/.?popAdsLoaded.?/)

Stiil, it has no effect on case javhub.net.

**Comment by gorhill** [comment]
I don't see any inline script tag with `popAdsLoaded` on that site, so the filter won't accomplish anything. For that kind of site, which will always try to pull in as much stuff from dubious 3rd parties, I suggest dynamic filtering with the following rules:

    javhub.net * 3p-script block
    javhub.net * 3p-frame block
    javhub.net ajax.googleapis.com * noop
    javhub.net openload.co * noop
    javhub.net openload.io * noop

![a](https://cloud.githubusercontent.com/assets/585534/12221599/4e66f1ea-b770-11e5-9ee2-9fb65a8ab80c.png)

Of course if you are already using uBO's medium mode, just adding the 3 last rules will be enough.

I don't get popups this way.

**Comment by olloff** [comment]
> I don't get popups this way.
Well, it sucks, because I still do. 

So let me explain my logic again.
Page javhub.net/...Mizuno contains page https://openload.co/embed/FDbkZ5f8Uv4 as iframe.
I got similar popups on both pages, so I believe, it caused by scripts on openload.co.
So I found next filter is sufficient to block popups on page https://openload.co/embed/FDbkZ5f8Uv4 (only as standalone page).

    openload.co##script:contains(/.*?popAdsLoaded.*?/)

Note the .*? crappy-regex is intended, because it helps eliminate 2 possible popup cases from that page. _popAdsLoaded_ encounters 3 times on that page - line 70 (packed into _var _0xa98d=_), line 73 and 94.

Sadly, I still have popups on page javhub.net/...Mizuno which contains page https://openload.co/embed/FDbkZ5f8Uv4 as iframe.
And that leads me to my question does it possible to use filter _script:contains()_ to scripts within iframe?

**Comment by gorhill** [comment]
> possible to use filter script:contains() to scripts within iframe?

Of course. The hostname name used as prefix is the context in which the filter will apply. This means that your original filter `openload.co##script:contains(/.*?popAdsLoaded.*?/)` will apply in `openload.co` pages and frames.

**Comment by gorhill** [comment]
Give me the detailed steps on how to get popups on that site (including which filter lists, rules).

**Comment by olloff** [comment]
@gorhill [Video proof here](https://app.box.com/s/5gn136gzbz3w0coz12bv4fvqmvq51vkx), sorry for quality/size.

1. Add filter _javhub.net##script:contains(/.*?popAdsLoaded.*?/)_
2. Move to [javhub.net](http://javhub.net/play/d122f1105/55c458aa6fb5fc4e25a6ad74/JUX-626-F-of-beauty-milf-play-with-temptation-younger-man-boss-Dirty-cum-Chaoyang-Mizuno)
3. Right-click anywhere on embedded video frame.
4. Notice popup being captured by browser.   
OR   
5. Left-click on center of embedded video frame.
6. Notice popup displayed and closed by uBo seconds after.
7. Video started prebuffering after 1-2 clicks (followed with popups).

This can be reproduced without filter stated before as-well.

1. Don't add any filters.
2. Move to [openload.co](https://openload.co/embed/FDbkZ5f8Uv4)
3. Right-click anywhere on video element.
4. Notice popup being captured by browser.
OR
5. Left-click on center of embedded video frame.
6. Notice popup displayed and closed by uBo seconds after.
7. Video started prebuffering after 1-2 clicks (followed with popups).

1. Add filter _openload.co##script:contains(/.*?popAdsLoaded.*?/)_
2. Move to [openload.co](https://openload.co/embed/FDbkZ5f8Uv4)
3. Right-click anywhere on video element.
4. Nothing happens.
OR
5. Left-click on center of embedded video frame.
6. Video started prebuffering instantly.

**Comment by gorhill** [comment]
Ok I see. The URL address of the embedded frame on `javhub.net` is not `openload.co`, it is `openload.io`. So re-write your filter as follow:

    openload.*##script:contains(/^\s*window.popAdsLoaded=/)

(I re-wrote your filter to be more efficient -- anchoring to the start will cause non-matching inline script tag to be scanned faster).

**Comment by gorhill** [comment]
I will add your filter to uBO's own filters btw, there is already something for `openload.co` in there.

**Comment by olloff** [comment]
Popups are still present on [javhub.net](http://javhub.net/play/d122f1105/55c458aa6fb5fc4e25a6ad74/JUX-626-F-of-beauty-milf-play-with-temptation-younger-man-boss-Dirty-cum-Chaoyang-Mizuno) with both filters enabled:

    openload.*##script:contains(/^\s*window.popAdsLoaded=/)
    javhub.net##script:contains(/^\s*window.popAdsLoaded=/)

> I re-wrote your filter to be more efficient

Thanks, regex is a real pain for me.

**Comment by gorhill** [comment]
You don't need the `javhub.net` one, there is no inline script tag with the string `window.popAdsLoaded=` on the page. I don't know how you get popups, I can't reproduce.

**Comment by IDKwhattoputhere** [comment]
Just wanted to confirm: No popups or popunders for me. No ads at all. Maybe @olloff is having malware issues? https://www.malwarebytes.org

**Comment by olloff** [comment]
_> malware issues_
Very reasonable and until new explanation I'm considering my system compromised. But popup in one random page would likely be a result of malware.
It also can be an targeting issue after all (I can be targeted for that popup by cookie or by geotargeting).

_> no inline script tag with the string window.popAdsLoaded= on the page_
Its true, they present only within an iframe - https://app.box.com/s/b82ikz2wt18945233o21gc6n2n96ym2q

Thanks for you time then. It was very nice of you two to help me.

**Comment by IDKwhattoputhere** [comment]
> It also can be an targeting issue after all

That might be the case.

However something odd happens when I try this in Firefox. First I have to activate the Anti-Adblock Killer by Reek‎ list because they are asking me to disable Adblock. https://cloud.githubusercontent.com/assets/16030872/12223834/5847226c-b7e2-11e5-96c2-aec68a898002.png
When I click the video, one of the popunders from openload.co's rotation opens and if it isn't for strict blocking it would load because Firefox asks me if I want to close my 2 tabs (I have two of them open before I click the video). It doesn't matter if I click "Close Tabs" or "Abort", uBO closes the popunder in both cases. I assume however that this is not intended since it makes the popunder filters useless against blocking the popunders from loading.
https://u.pomf.is/efngkf.mp4
If this is unrelated I can open a new issue.

**Comment by gorhill** [comment]
> they are asking me to disable Adblock

Be sure all your filter lists are up to date. The page is all clean here, no need for Reek‎'s list either -- just using default settings.

**Comment by IDKwhattoputhere** [comment]
Yes, I set up a new Firefox profile and installed uBO but since the lists are bundled they weren't up to date anymore. Now I don't get an anti-adblock message anymore. The issue from the video still exists though.

**Comment by olloff** [comment]
_>  is this perhaps what * was talking about?_
Welcome to the Sgt. Pepper's Shitty Popups Club, that's exactly I was talking about.

**Comment by gorhill** [comment]
@olloff I think I might have introduced a regression bug in last update concerning inline script tag filter which could explain the issue here (code change for #838). Will investigate a bit more.

**Comment by gorhill** [comment]
Fixed with 5591ff34f1a47adca847d52979ce98f64663c16f => 1.5.4 pushed to AMO.

**Comment by olloff** [comment]
-Please, feel free to ask if you will need something.-

It works. Oh, wow, that was really fast!

**Comment by IDKwhattoputhere** [comment]
The problem demonstrated in the video still exists with uBO 1.5.5

**Comment by gorhill** [comment]
> Should I open a new detailed issue?

Yes, open a new issue, this is a different one.

Does this also happen with Chromium?

**Comment by IDKwhattoputhere** [comment]
No, it doesn't happen. Chromium doesn't ask the user before quitting a session with multiple tabs open. Only Firefox does.

**Comment by gorhill** [comment]
> No, it doesn't happen

Did you try? The question is not whether Chromium asks before quitting, the question is whether the popup is properly closed in the first place.

**Comment by IDKwhattoputhere** [comment]
I tried and it did get blocked. It seems to try to get opened in a new tab instead of a new window like in Firefox but gets immediately closed like expected.

**Comment by gorhill** [comment]
Ok, this is becoming a lot of noise in an otherwise unrelated issue. I haven't been able to ever reproduce what you recorded here: <https://u.pomf.is/efngkf.mp4>. Try again with latest dev build -- maybe this was a similar issue as #1305. Otherwise open a new issue with all that is needed for anybody to reproduce.
