### ISSUE TITLE
Element picker does not offer a filter to block the clicked video element

### ISSUE THREAD

**Issue by 7even6ix2wo** [gorhill/uBlock#1545]
### Describe the issue
I have blocked the video playing layer on this website with the element picker tool.  It took three or four blocking actions to make the video rectangle no longer appear on the screen.  However, the sound keeps autoplaying and I cannot locate the audio player element.  How can I block the sound from autoplaying?  I hate when the sounds starts when I'm trying to read the article!

### One or more specific URLs where the issue occurs
http://www.usatoday.com/story/news/politics/2016/04/07/va-wait-time-manipulation-veterans/82726634/

### Steps for anyone to reproduce the issue
1. Go to website.
2. Block the video element.  Keep using the element picker to block that area until it is gone. (May require multiple refreshes)
3. Observe that the video element no longer loads but the sound still starts automatically.

### Your settings
My settings are 100% default for uBlock Origin 1.6.8
I am using Firefox 45.0.1 in Windows 7 Home Premium 64

##### Your filter lists
Default filer list only.

**Comment by RoxKilly** [comment]
@7even6ix2wo This doesn't answer your question directly but may help solve your root problem: 
>  I hate when the sounds starts when I'm trying to read the article!

In Firefox, go to `about:config`, search for the setting `media.autoplay.enabled` and set it to `false` by double-clicking it.  This will prevent media items from play automatically when a webpage loads.

**Comment by gorhill** [comment]
Related #868.

Still, uBO should at least offer to create the proper network filters for audio/video elements.

**Comment by 7even6ix2wo** [comment]
Thanks RoxKilly.  Something that affects the browser behavior so profoundly shouldn't be hidden in about:config but now I know!  Thanks gorhill, I like your app a lot.

**Comment by gorhill** [comment]
Changed the issue title to reflect what I consider to be the real issue.

**Comment by gorhill** [comment]
Fixed with def2b7cbffa633a7f199ea33dbc5646b07d565f3.

**Comment by 7even6ix2wo** [comment]
How can I use that solution?  I went to the web page and still have the problem.   Where can I DL that version?

**Comment by IDKwhattoputhere** [comment]
https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md#before-you-submit
Read point 5.

**Comment by 7even6ix2wo** [comment]
I don't give a fuck about point 5 or your fucking post.
