### ISSUE TITLE
messenger.com not displaying, unsure how to resolve

### ISSUE THREAD

**Issue by collincusce** [gorhill/uBlock#2770]
Filter issues **MUST NOT** be reported here. Read first: <https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md>

### Describe the issue
Going to http://messenger.com displays a blank page. Disable uBlock and it re-appears.

See picture.

### One or more specific URLs where the issue occurs

http://messenger.com

### Screenshot in which the issue can be seen

http://i.imgur.com/yGWfrvu.png

### Steps for anyone to reproduce the issue

1. in Chrome Version 59.0.3071.115 (Official Build) (64-bit) on Windows 10
1. Clear cache and local storage
1. navigate to http://messenger.com
1. Behold the blankness
1. Witness the error presented in screen capture
1. Disable uBlock Origin and refresh
1. Glare at the evils that is Facebook Messenger as it displays properly!
1. Re-enable uBlock Origin
1. Rejoice in the blankness!

### Your settings

[If you fail to provide this info, I will mark the issue as invalid. Lists all settings which differs from default settings]

- OS/version: Windows 10 64bit
- Browser/version: Version 59.0.3071.115 (Official Build) (64-bit)
- uBlock Origin version: 1.13.2

##### Your filter lists

http://imgur.com/vFFsi6R.png

http://imgur.com/WFanx9r.png

##### Your custom filters (if any)

N/A

**Comment by gorhill** [comment]
Closing and marking as _invalid_, as per [CONTRIBUTING](https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md).

**Comment by bershan2** [comment]
I see rule `###facebook` in **RUS: BitBlock List**, but this filter is not enabled by default. When I disable the list the page loads properly.

**Comment by gorhill** [comment]
Fixed in 3rd-party EasyList hours ago:<https://github.com/easylist/easylist/commit/49e2a5f88da780a892112076feb25c280ba56132>.

**Comment by bershan2** [comment]
Apparently, there is another bad rule in **RUS: BitBlock List** `###facebook` and it was not fixed yet according to the forum.
https://forums.lanik.us/viewtopic.php?f=64&t=37415&p=120637&hilit=messenger#p120637

**Comment by collincusce** [comment]
Yeah I'm still having the issue. Amazing response times, though! Dang! I'm commenting on the easy list repo instead.

**Comment by bershan2** [comment]
**RUS: BitBlock List** issue was fixed, `bitblock/social_general_hide.txt` was modified as follows:
```
-~facebook.com###facebook
+~facebook.com,~messenger.com###facebook
```
https://hg.adblockplus.org/ruadlist/rev/d3d77e43242e
