### ISSUE TITLE
Sync issues with all versions above 11.3.8

### ISSUE THREAD

**Issue by alexolog** [gorhill/uBlock#3022]
I run FF 55 (latest 64bit) at home on Win 10 and 52 ESR (latest 64bit) at work on Win 8.1
(However, that problem also happened when I tried to run FF 55 at work, so it is likely not caused by different FF versions)

If I try to upgrade uBO on one of the machines to a more recent version (currently any release up to 11.4.8), it no longer sees the uploaded data from the other.  Once I downgrade to 11.3.8 again, the data becomes visible and syncable once more.

**This is from 11.3.8, running at home:**

![ubo1138](https://user-images.githubusercontent.com/2112513/30509155-6838bd1a-9a77-11e7-9e68-aa55af63e045.jpg)

**And this is from 11.4.8, also running at home:**

![ubo1148](https://user-images.githubusercontent.com/2112513/30509163-8faaf35e-9a77-11e7-9203-14de1fff7c06.jpg)

No matter what I do, I can't make the newer versions see the other machine's data.

Another thing I noticed, is that when I open the uBO 1.14.8 settings, I get the following in the console:

```
[Exception... "Illegal value"  nsresult: "0x80070057 (NS_ERROR_ILLEGAL_VALUE)"  location: "JS frame :: chrome://browser/content/ext-tabs.js :: query :: line 482"  data: no]  (unknown)
	query chrome://browser/content/ext-tabs.js:482:29
	InterpretGeneratorResume self-hosted:1272:8
	next self-hosted:1179:9
	query self-hosted:943:17
	call resource://gre/modules/ExtensionParent.jsm:617:24
	next self-hosted:1179:9
```

But with 11.3.8, I see a different error:
```
	NS_ERROR_UNEXPECTED: Component returned failure code: 0x8000ffff (NS_ERROR_UNEXPECTED) [nsISyncMessageSender.sendSyncMessage]  content.js:987
```

**Comment by Betsy25** [comment]
Yes, it's a know bug which apparently was fixed in the latest [pre-release](https://github.com/gorhill/uBlock/releases/tag/1.14.11b0).

**Comment by gorhill** [comment]
> If I try to upgrade uBO on one of the machines to a more recent version (currently any release up to 11.4.8), it no longer sees the uploaded data from the other

That is expected, the cloud storage data is stored differently with the WebExtensions API.

uBO/legacy was saving the data in `about:config`, now it is saved by Firefox _somewhere_, which uBO has no idea, it just uses the WebExtensions API framework `browser.storage.sync`.

**Comment by alexolog** [comment]
So I tried upgrading both instances to the latest version.
Results: Each instance sees only it's own storage, so I still cannot sync.

When I open the uBO settings, I get the following in the console:
```
ReferenceError: reference to undefined property "broadcast"[Learn More]  vapi-client.js:136:1
Invalid match pattern: 'moz-extension://bb2d38bc-a993-4b39-b3e1-12238d97dbbc/dashboard.html'  MatchPattern.jsm:52
	SingleMatchPattern resource://gre/modules/MatchPattern.jsm:52:7
	this.MatchPattern resource://gre/modules/MatchPattern.jsm:109:22
	self.tabs.query chrome://browser/content/ext-tabs.js:673:21
	bound  self-hosted:915:17
	call resource://gre/modules/ExtensionParent.jsm:474:64
	receiveMessage resource://gre/modules/ExtensionParent.jsm:403:9
TypeError: can't access dead object  action.js:463:1
ReferenceError: reference to undefined property "do"[Learn More]  content.js:32:1
ReferenceError: reference to undefined property "broadcast"[Learn More]  vapi-client.js:136:1
```

I am at a loss.  Is there anything else I can check?

**Comment by jaywk** [comment]
@gorhill seeing as you closed this and answered by saying this is  expected behavior with the WebExtension API, is sync functionality no longer possible? If so, the functionality and option to use cloud storage should be removed from the settings page.

**Comment by gorhill** [comment]
@jaywk I didn't say anywhere "sync functionality no longer possible", I said uBO/webext can't see data in the legacy cloud storage.

**Comment by lemmy04** [comment]
uBO/webext also cannot see data from other instances of the same FF version syncing into the same mozilla account.

**Comment by lemmy04** [comment]
now I am trying to push the data, and I get "Please set webextensions.storage.sync.enabled to true in about:config". That setting was disabled, let's see if it works properly when changing it.

**Comment by lemmy04** [comment]
hm. even with that flag set to true I can *not* use the cloud storage to sync settings between devices.

**Comment by gorhill** [comment]
I and others have successfully used cloud storage. See `about:sync-log` says. Be sure "Add-ons" is selected in Sync options. Other than this, you will have to investigate on your side what is preventing it from working.

**Comment by jaywk** [comment]
For me the problem seemed to be that background syncing was not occurring. The data does sync if I initiate a manual sync from both machines.

**Comment by gorhill** [comment]
> For me the problem seemed to be that background syncing was not occurring.

That would be a Firefox-side issue -- uBO merely just use the API to save stuff, beyond this, Firefox is responsible to send that stuff to its cloud storage server.

**Comment by lemmy04** [comment]
do i give all devices the same name in uBlock?

**Comment by gorhill** [comment]
No, this is simply for you to know from which device the data last came from.

**Comment by lemmy04** [comment]
see my comment on #3113
