### ISSUE TITLE
uBlock lists domains that are blocked by FF tracking protection

### ISSUE THREAD

**Issue by RalfJung** [gorhill/uBlock#3231]
Filter issues **MUST NOT** be reported here. Read first: <https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md>

### Describe the issue

Comparing the output of the Firefox debugger "Network" tab and the uBlock logger, uBlock lists more requests than Firefox. Looking at Wireshark, it seems that Firefox is right and uBlock is wrong.

On closer inspection, it seems that FF tracking protection kicks in *after* uBlock and hence uBlock reports incorrect information.

### One or more specific URLs where the issue occurs

I have been debugging this on <https://plv.mpi-sws.org/mtac/>. uBlock shows accesses to twitter, but there are none.

### Steps for anyone to reproduce the issue

1. Go to <https://plv.mpi-sws.org/mtac/>
2.  Open the uBlock logger
3. Hit F12, open the network tab.
4. Do a shift-click on the reload button.
5. Compare the requests listed by Firefox, and those listed by uBlock.

### Your settings

[If you fail to provide this info, I will mark the issue as invalid. Lists all settings which differs from default settings]

- OS/version: Linux, amd64
- Browser/version: Firefox 57
- uBlock Origin version: 1.14.19b5

##### Your filter lists

Default + Fanboy's Annoyance

**Comment by gorhill** [comment]
> uBlock shows accesses to twitter, but there are none.

There are network requests to Twitter.

**Comment by RalfJung** [comment]
> There are network requests to Twitter.

There are not. Not if you have tracking protection enabled. I traced all my https network traffic with Wireshark, the only host that is contacted is plv.mpi-sws.org.

**Comment by gorhill** [comment]
Ok, I tested using Firefox Nightly instead of Firefox 56 (I don't have stable 57 yet). I can reproduce the network pane not reporting `twitter.com`, while uBO's logger report `https://platform.twitter.com/widgets.js`. I still don't see what is the issue, uBO reports what goes through its `webRequest` API, and it reports **what it did itself** to a network request, not what something else outside its realm did to a network request, by design.

uBO-Scope does that however, and it reports accurately that the network request to `twitter.com` was blocked.

**Comment by gorhill** [comment]
Given what I have observed here, I corrected my bad information on Reddit: <https://www.reddit.com/r/firefox/comments/7ci74s/firefox_to_offer_tracking_protection_for_all_in/dpr1eyz/>.

**Comment by RalfJung** [comment]
> I still don't see what is the issue, uBO reports what goes through its webRequest API, and it reports what it did itself to a network request, not what something else outside its realm did to a network request, by design.

It would be nice if uBO would work better with Firefox' tracking protection -- I was rather confused for a while when I saw some requests still getting through uBO that I did not want, but could not find them in the network pane. I mostly noticed this in uBO's "blocked domain" list in the popup, where it says the page contacted twitter.com while it did not.
