### ISSUE TITLE
HTML Filter with ^ has no effect

### ISSUE THREAD

**Issue by theseer** [gorhill/uBlock#3562]
Based on the documentation for [html-filters](https://github.com/gorhill/uBlock/wiki/Static-filter-syntax#html-filters), the only _syntactical_ difference to the cosmetic filters seems to be the ^-prefix.

It is my understanding that a match would remove the element specified from the html before the stream hits the rendering engine.

Yet, when adding a such a filter it does not seem to have any effect?
When omitting the ^-prefix, the element gets hidden as expected, so I assume the selector itself to be correct.

I'm not sure whether I'm doing something wrong and it's behaving as expected or this is a bug.

I tried this with my company website: https://thephp.cc/welcome with the following simple filter to hide respectively remove the Home link from the top menu bar.

The cosmetic filter `thephp.cc##a:has-text(Home)` works as expected, the a element gets hidden but remains in the dom. The html filter `thephp.cc##^a:has-text(Home)`  though has no effect.

- OS/version: Fedora 27
- Browser/version: Firefox 58.0.2 (64-bit), Fedora build
- uBlock Origin version:  v1.15.11b5, also tried 1.15.10 before

**Comment by gorhill** [comment]
Thanks for reporting.

There is an error in the regex I used to detect content type. However, once I fixed the error, this uncovered another issue with the HTML filtering code which occurred as a result of parsing the XHTML document (served at `https://thephp.cc/welcome`) as a HTML one. So this needs fixing too.

**Comment by theseer** [comment]
That's what I call a quick fix. Thanks so much! 

And also thanks for pointing out wrong mime type for our company website. Guess I have some fixing to do as well.

**Comment by gorhill** [comment]
Your mime type is fine, it's uBO which was not using it to pass to DOMParser, I was passing a hard coded `text/html`.

**Comment by Raaviz** [comment]
@gorhill 

### Describe the issue

It seems that is has been fixed partially only, because still exception HTML filters like `#@#^` don't work.

### One or more specific URLs where the issue occurs

Any, for ex. https://pl.wikipedia.org

### Screenshot in which the issue can be seen

![capture_003_03032018_082158](https://user-images.githubusercontent.com/36993809/36931720-2ce4d248-1ebc-11e8-88ca-5c2dd9faad9c.png)

### Steps for anyone to reproduce the issue

1 Add the custom filters.
2. Launch the logger.
3. Visit the website.
4. Notice in the logger that there is no exception filter, still the regular filter appears instead.


### Your settings

OS/version: Win 7 U SP1 64bit
Browser/version: Firefox 58.0.2 64bit
uBlock Origin version: 1.15.10, v1.15.11b(5/6)

##### Your filter lists

None

##### Your custom filters (if any)

`pl.wikipedia.org##^script:has-text(window.RLQ)`
`pl.wikipedia.org#@#^script:has-text(window.RLQ)`

**Comment by owhous** [comment]
@gorhill problem is not fixed on youtube.com and duckduckgo.com

**Comment by gorhill** [comment]
I am not aware of any issue with HTML filtering on youtube.com and duckduckgo.com. If you uncovered an issue with uBO, open a new issue with all the needed details for others to reproduce as requried. Also, be sure to read the documentation before so that you understand what exactly is HTML filtering.
