### ISSUE TITLE
Incompatibility With Lastpass

### ISSUE THREAD

**Issue by gary-hammer** [gorhill/uBlock#443]
- A URL where the issue systematically occurs
- Preferably a site where it's not too much of a hassle to create a throwaway account
  Facebook, Outlook.com, Google
- Special Lastpass setting where they differ from default
  None, just install and use.
- uBlock settings where they differ from default
  None, just installed it and I get the issue. 
- Non-default filter lists
  None
- Custom filters
  None

All I need to do is install this and lastpass, then go to almost any site with a login to have lastpass fail.
Disabling uBlock for a page or a site does not fix the problem. DIsabling uBlock from plugin manager does.

ABP does not have this issue.

**Comment by alejandrolemus** [comment]
I use Lastpass and uBlock origin, no issue here, except it very rarely fails to load manually from the text field markers. But other than that, it works 99% of the time. Latest Firefox on Windows 7.

**Comment by PepsiGuy** [comment]
Win 10, I'm attaching two images of what happens.
![lp-1_cr](https://cloud.githubusercontent.com/assets/12861605/8509147/91fc8e60-2260-11e5-88ae-df11468a5a21.png)
![lp-2_cr](https://cloud.githubusercontent.com/assets/12861605/8509148/91fe560a-2260-11e5-9145-9e822e7a5869.png)

**Comment by gorhill** [comment]
I tried using the provided details and Lastpass worked all fine. So there are other details than what is provided that are needed to reproduce the issue.

**Comment by PepsiGuy** [comment]
Very odd.
Right now I have two enabled add-ons, Lastpass 3.2.1.1 and uBlock Origin 0.9.9.3.
I reset (via the provided reset to default button) all preferences in Lastpass.
Perhaps a new profile then?
Back after giving that a try.

**Comment by gorhill** [comment]
> Lastpass 3.2.1.1

The one I installed from AMO says 0.3.4.

**Comment by PepsiGuy** [comment]
Also has this one
 LastPass Password Manager 3.1.95 

I think I will remove LP, then reinstall it from AMO again.
The one I'm using came from LP website and was a universal installer.

**Comment by PepsiGuy** [comment]
Presto! Remove and install from AMO. Working fine. Off to LP and open an issue.
Odd that this didn't happen with ABP, but, I'd much rather use uBlock Origin.
I shall go update the review now as well.

**Comment by PepsiGuy** [comment]
There is someone else confirming my 'issue'. I have made clear in the edited review what the issue and fix were.

**Comment by gorhill** [comment]
I would like to understand what is happening. At first I would have thought it's a cosmetic filter interfering, but you say that disabling uBlock does not solve the issue, so I can't think of a scenario which would cause such problem. If it's possible to link here the related issue on Lastpass, I will follow it.

**Comment by PepsiGuy** [comment]
By disabling, I mean from the 'power' icon, or by disabling it on the page or site.
Disabling from Add-ons manager is what does in fact allow LP to work.
Now though, LP is working with the 3.1.9.5 installed from AMO

There is no way I can find to open an issue with LP, just a problem form.
Here is who has replied to me. Not helpful though as he can't replicate the issue...
"Andrew Zitnay <drew@lastpass.com>

I'm unable to reproduce either issue.  Perhaps you can include screenshots of both.
The fact that you're not seeing either the field icons or the notification bar might actually be related, since they both inject an iframe into the page.  If you go to the JavaScript console via Ctrl+Shift+J immediately after one or the other was supposed to appear, do you see any related errors? "

**Comment by gorhill** [comment]
> Lastpass 3.2.1.1

I can't see a 3.2.1.1 for Firefox on [that page](https://lastpass.com/misc_download2.php).

**Comment by PepsiGuy** [comment]
https://rodan.lastpass.com/dev/lp_e10s.xpi

**Comment by gorhill** [comment]
> https://rodan.lastpass.com/dev/lp_e10s.xpi

I could reproduce using above package. Here is what the browser console reports each time I click on the login fields:

![c](https://cloud.githubusercontent.com/assets/585534/8509335/c969102a-226b-11e5-8757-f7ddb50acc9c.png)

**Comment by PepsiGuy** [comment]
Excellent! I shall pass that along.

**Comment by gorhill** [comment]
Ok, an important piece of information I guess. If I disable uBlock, the `iframe` appears correctly. 

However, the browser console spams errors related to `nsSidebar.js: 19:0` as seen above, i.e. the count keep going up fast and it does not stop (100s). The difference is that the error count with uBlock is limited. So it appears that there is an issue independent of uBlock, but it manifest differently in the presence of uBlock.

**Comment by PepsiGuy** [comment]
I agree, useful info.

**Comment by gorhill** [comment]
Any news from LastPass about this?

**Comment by PepsiGuy** [comment]
I got an early reply, but haven’t heard from them. Let me rattle their cage a bit.

**Comment by PepsiGuy** [comment]
Well, it seems Lastpass wants to put the ball in your court.
Here's their reply:
"uBlock is blocking our iframes.  The uBlock developer really needs to look into why."
If you'd like their email, let me know.

**Comment by gorhill** [comment]
> it seems Lastpass wants to put the ball in your court

uBlock works fine with their non-dev version.

Without uBlock: their popup generates 20 errors per second in the browser console, and it never stops unless you close the popup. It appears their login frame is removed/added non-stop. They are paid developer, I am not going to do the work to pinpoint their bug.

**Comment by PepsiGuy** [comment]
That’s exactly what I’ve told them and shown them. Hey, I much easier believe a new, test version is more likely to be broken than something that has worked well for me. Thanks for taking a look as these two add-on are the only ones I use and both are absolutely necessary to me.

 

My final response from them was this, the link to the test build looks exatly the same and performs the same.

 

“The new build has to inject the iframe in a different way.  uBlock is blocking this new method.

We're certainly not removing and adding the iframe nonstop.  As for the errors, I've managed to make a change to avoid them:

https://rodan.lastpass.com/dev/lp_e10s.xpi”

**Comment by azitnay** [comment]
The errors in the browser console were unrelated, and have been resolved in this build:

https://rodan.lastpass.com/dev/lp_e10s.xpi

We are certainly not adding and removing the iframe nonstop.  The bottom line here is that our new e10s-compatible extension adds the iframe in a different manner, which uBlock is clearly blocking for some reason.  We're able to insert our iframe without issue when uBlok isn't installed.

**Comment by gorhill** [comment]
> We are certainly not adding and removing the iframe nonstop

Ok. However, when your `iframe` is added, the DOM inspector becomes hardly usable, there is some non-stop DOM mutation going on in there. For example, if I select an attribute of your `iframe` in the DOM inspector to say manually change its value, I can't, the caret's focus is always reset. So on my side, without uBlock, even the DOM inspector become affected as soon as the LastPass `iframe` is added to the page. When the `iframe` is removed, the DOM inspector is back to be usable.

**Comment by gorhill** [comment]
> https://rodan.lastpass.com/dev/lp_e10s.xpi

I tried with that build and the DOM inspector issue is still there. It looks like the `style` property of your `iframe` is constantly being written to. Just bringing up that LastPass popup causes FF CPU usage to inch up, until the LP popup is closed -- worse if the DOM inspector is opened.

With uBlock, your `iframe` is **not** blocked. The only thing uBlock does is to listen to the `src` property change on `iframe` element. In the current case, this does absolutely nothing, since there is no filter in uBlock to block your `iframe` -- uBlock does not touch it further after evaluating it only once. I can see your `iframe` in the (crippled) DOM inspector, and its `display` style property is `block !important`, so uBlock did not touch it.

The first thing I would do is to address whatever causes LastPass to cripple the DOM inspector when that `iframe` is added.

**Comment by azitnay** [comment]
I've drastically cut down on the number of times we update the iframe's style property:

https://rodan.lastpass.com/dev/lp_e10s.xpi

I'm not sure how you can claim that uBlock isn't causing the issue, given that it works perfectly with uBlock disabled.  Perhaps a little background on how the iframe is inserted will help, since it's pretty complicated.  Due to changes required for e10s compatibility, we're forced to give the iframe an initial src looking something like:

https://83180625.fieldtrials.tivo.com/lpblankiframe.local

Then, within a frame script, we listen for the DOMWindowCreated event, and change the iframe's location.href to something like:

resource://support-at-lastpass-dot-com/lastpass/data/popupfilltab.html?lplanguage=

The last step is what's broken with uBlock enabled.  popupfilltab.html is never loaded.

**Comment by gorhill** [comment]
> https://rodan.lastpass.com/dev/lp_e10s.xpi

The DOM inspector is still crippled, there is still something else in there modifying the DOM many times per second such that the Firefox DOM inspector does not work too well.

> I'm not sure how you can claim that uBlock isn't causing the issue

Because I traced into the code and the `iframe` is not touched by uBlock. uBlock merely install a mutation observer for the `iframe`.

I have narrowed to [**one line** in uBlock which causes LastPass to fail](https://github.com/gorhill/uBlock/blob/bd43babf757235eb571ab4c6a1c912e8725d58d5/platform/firefox/frameModule.js#L173):

    context = context.contentWindow;

If that specific line is not executed, the LastPass popup appears. If that specific line is executed, the LastPass popup won't appear. So _merely_ looking up the `contentWindow` property causes the LastPass popup to not appear, and obviously this has nothing to do with uBlock blocking the popup (which it doesn't anyways as stated earlier).

**Comment by azitnay** [comment]
I fixed another case where we were inserting a DOM node many times per second.  I think it's good now:

https://rodan.lastpass.com/dev/lp_e10s.xpi

If that line is truly causing the issue, then it doesn't seem like this issue is being caused by either LastPass or uBlock.  Seems more like an odd quirk/bug in Firefox itself.

In lieu of a Firefox fix, I suppose the only way we could work around this issue would be for you to not run this code for our iframe.  Alternatively, is there any rule users can put in place within uBlock to skip this code for a specific iframe?

**Comment by gorhill** [comment]
A related issue on bugzilla: <https://bugzilla.mozilla.org/show_bug.cgi?id=1008768>.
