### ISSUE TITLE
question/suggestion: centralized custom filter/whitelist settings?

### ISSUE THREAD

**Issue by jdsemma** [gorhill/uBlock#832]
Background: I have a number of Chromebooks under managed enrollment in a Google Apps domain. I'd like to push uBlock Origin out to all of them (which we can easily do), but I'd also like to be able to create our own custom filter (actually mostly whitelists) and also push that out to all of the Chromebooks. If the app/extension is set up to support a config file, we can easily do that through Google Apps as well.

Can this be done, and if not currently, can it be put on the feature request list?

(Edited to add: more info on config files here: http://www.chromium.org/administrators/configuring-policy-for-extensions)

**Comment by gorhill** [comment]
If I understand correctly what you want to accomplish, it's [already supported in Firefox](https://github.com/gorhill/uBlock/releases/tag/1.0.0.1). However for Chromium-based browsers, I have been waiting for such request so that I can test the code I need to hook to `chrome.storage.managed`.

I will let you know when I have something.

**Comment by jdsemma** [comment]
Yes, exactly. Thank you for considering this! And yes, obviously, for use on Chromebooks this is Chromium-based (although I have no idea where the config file is stores on ChromeOS.)

**Comment by gorhill** [comment]
Implemented in [1.3.2b2](https://github.com/gorhill/uBlock/releases). I will need you to validate whether this works, I do not have the environment to test this.

**Comment by jdsemma** [comment]
I tested, but can't tell if my test config file isn't right (although it loads without error), or if this isn't working.

For a test config file, I went to uBlock options (after adding specific things to the whitelist) and did 'backup to file'. I then loaded that file into the Chrome App Management tool, and forced the app to auto-install to a specific testing user. The user gets the app just fine, but only with the default config. The config I installed isn't being pushed across.

Thinking after reading more that the config will only look for "adminSettings", I made a new config file like this:

{
  "timeStamp": 1446240370977,
  "version": "1.3.2",
  "adminSettings": {"colorBlindFriendly": true } 
}

That's it. I loaded that, no errors, but the config isn't being pushed out.  Confirmed via chrome://policy that no policies are being loaded for uBlock Origin.

(Ideally I'd like to be able to push a custom netWhitelist addition, but I'll be satisfied with being able to add to externalLists.)

**Comment by gorhill** [comment]
> Thinking after reading more that the config will only look for "adminSettings", I made a new config file like this:

That's not a valid backup file, it contains nothing of value for uBO. Try:

    {
        "userSettings": {
            "colorBlindFriendly": true
    }

What I did is:

- Open a backup create from clicking the uBO's _"Backup to file"_.
- Remove all entries which are not to be overwritten.

Now, assign the resulting string (it must pass as a valid JSON string) to the entry `adminSettings` in the managed storage. That last part I am assuming admins know how to to this, I don't know myself, I just read from the managed storage (it's read-only from an extension's point of view).

**Comment by jdsemma** [comment]
I am guessing wildly as to how to set up the config file, based on the example given at http://www.chromium.org/administrators/configuring-policy-for-extensions.

I've tried

```
{ "adminSettings": { "Value": [ { "userSettings": [ {"colorBlindFriendly": true } ] } ] } }
```

(after running that through jsonlint to make sure it's valid), and.... no value is being assigned to adminSettings.

**Comment by gorhill** [comment]
The value of `adminSettings` is supposed to be a valid JSON string, I see it is set to an array of `object` in your snippet. A valid JSON string of what you are trying is:

    { "userSettings": { "colorBlindFriendly": true } }

(there was a typo in my above example, I just fixed it).

**Comment by jdsemma** [comment]
So:

```
{ "adminSettings": { "Value": { "userSettings": {"colorBlindFriendly": true } } } }
```

?

Tried that, still says no policy set.

**Comment by gorhill** [comment]
Ok, I followed the doc for Linux, and it worked here. I created a JSON policy file name `ublock0,json` in `/etc/opt/chrome/policies/managed/`, and this is the content of the file:

    {
      "3rdparty": {
        "extensions": {
          "pbffolnficoggnnamkphaffidiafpeaf": {
            "adminSettings": "{ \"userSettings\": {\"colorBlindFriendly\": true } }"
          }
        }
      }
    }

Then I restarted Chrome, and the _"Color blind friendly"_ setting was checked. For other OS, I can't tell.

**Comment by gorhill** [comment]
Note that I mentioned, I rely on feedback to fine-tune this, and I think I will also offer the ability to encode the value as plain JSON -- not force a stringified JSON, to enable not having to escape double-quotes.

**Comment by jdsemma** [comment]
Sounds like. I tried this:

```
{ "adminSettings": { "Value": { \"userSettings\": {\"colorBlindFriendly\": true } } } }
```

and still no dice.

**Comment by gorhill** [comment]
Your JSON [does not pass validation](http://jsonlint.com/).

Try:

    { "adminSettings": { "Value": "{ \"userSettings\": {\"colorBlindFriendly\": true } }" } }

**Comment by jdsemma** [comment]
Duh. :)

I tried that and..... almost success!

The policy is set, according to chrome://policy. The policy value, literally is

```
{ "userSettings": { "colorBlindFriendly": true }}
```

However, in uBlock's options, that setting is NOT set to true. It's still false.

**Comment by benwa** [comment]
I just tried and got it to work.  I am on Windows however and had to actually edit the registry.
![image](https://cloud.githubusercontent.com/assets/1351571/11186430/a732c016-8c4f-11e5-99da-cec87a58048e.png)

Then I went to chrome:policy and clicked reload.
![image](https://cloud.githubusercontent.com/assets/1351571/11186454/c461100c-8c4f-11e5-87a1-eacb1fa18c19.png)

Refreshing the options page didn't do anything, I had to actually disable the extension and then reload it.
![image](https://cloud.githubusercontent.com/assets/1351571/11186523/0355f232-8c50-11e5-9a1f-f4bcd8b3aaa0.png)

Is there an event listener for storage option changes?  That would stop the need of reloading the extension.

Also, it seems these settings aren't actually mandatory (or at least the options page UI doesn't indicate it as you can uncheck and it will save).

**Comment by jdsemma** [comment]
I still can't get userSettings to be set, but I did successfully get a netWhitelist to stay. I loaded this:

```
{ "adminSettings": { "Value": "{ \"netWhitelist\": \"about-scheme\\nbehind-the-scene\\nchrome-extension-scheme\\nchrome-scheme\\nloopconversation.about-scheme\\nopera-scheme\\npastebin.com\\nMYDOMAIN.com\\MYOTHERDOMAIN.com\" }" } }
```

(domain names edited to protect the guilty). This did properly load.

**Comment by dXcess** [comment]
First and foremost - gorhill - that you for your efforts with this, its a huge help. I'm hoping that I can contribute to this somehow by creating a policy template for Windows users, that will make it easier to manage these settings from Windows.

benwa,
i've tried the same as you via the registry, and just cant seem to get it to work. The policies never load in chrome, no matter what I try. I'm using version 1.3.3. of UBO.

![image](https://cloud.githubusercontent.com/assets/16167165/11608664/f125dd64-9b3d-11e5-8d95-acbf12a658eb.png)

![image](https://cloud.githubusercontent.com/assets/16167165/11608671/22fba242-9b3e-11e5-998b-e6083fbbc608.png)


Can you share the reg export for help shed some light?

**Comment by benwa** [comment]
It could possibly be white space or different quote characters.  Before I deployed via Group Policy Preferences, I wrote out the preferences [here](http://codebeautify.org/jsonviewer) and then used Minify to set it all to one line.

**Comment by IRainman** [comment]
It is necessary .admx and .adml files for use in the GPO on Windows, without setting through the policy files in the Chrome settings do not work and do not apply :(

**Comment by killebrewj** [comment]
This is great! I was able to deploy a custom whitelist to some Chromebooks and Chrome browsers. 

The only thing is if I change the policy and the browser receives the new policy, uBlock doesn't actually use the new settings until the next time the browser starts up or you can force it by reloading the extension (as benwa said). Is there any way to have it periodically check and apply the currently loaded policy?

Or is it possible I was just being too impatient?

**Comment by edlisten** [comment]
I am a GAFE admin with managed Chromebooks that I would like to deploy uBlock Origin to.   I have pushed the extension out to users, and created the custom JSON file, but I am missing how do I distribute the JSON file out to all the users?

**Comment by gorhill** [comment]
I have a Chrome dev version for testing, and I use a policy on it to validate that policy settings work:

![a](https://cloud.githubusercontent.com/assets/585534/15591895/d5ae385c-236d-11e6-8f80-b6e7da1c4cc4.png)

I actually forgot how I created this entry... You are probably better placed than me to figure this. But as you can see, the value is `adminSettings`, and the value must be a JSON-valid string which matches the output you get when creating a backup of the settings, minus the entries which you do not want to enforce on all users.

**Comment by killebrewj** [comment]
If you're using Google Apps, you need to deploy the extension to your users by navigating to Device management > Chrome > Chrome App Management

![image](https://cloud.githubusercontent.com/assets/15217481/15592725/f67f8bf2-235a-11e6-94bd-b3374e2bfbe2.png)

Once added, click the app and expand User settings. Pick the OU, Force Install and click UPLOAD CONFIGURATION FILE and then select the text file containing the json configuration.

![image](https://cloud.githubusercontent.com/assets/15217481/15592789/6e054342-235b-11e6-8724-58b01568c20f.png)

The json is not necessarily a full config dumped from uBlock. Ours is just a simple whitelist. This is the full content of our configuration file. It's a bit ugly having to nest json inside json and it might get messy with a large whitelist.

{ "adminSettings": { "Value": "{ \"netWhitelist\": \"about-scheme\\nbehind-the-scene\\nchrome-extension-scheme\\nchrome-scheme\\nloopconversation.about-scheme\\nopera-scheme\\ndomain.com\\nanotherdomain.org\\ndomain.ca.us\" }" } }

**Comment by edlisten** [comment]
Ahh, the missing link.    I was installing the extension from the user
settings and never even knew about chrome app management.   Thank you.

**Comment by edlisten** [comment]
@killebrewj I am almost there.   I was able to create a JSON, file upload it and have it show up in chrome://policies.   I have restarted the Chromebook and reloaded the extension, but I don't see any of the sites I have added in the whitelist of uBlock Origin.

**Comment by gorhill** [comment]
Did you check your JSON string with a JSON validator<sup>[1]</sup> to be sure it's properly formed?

[1] <http://jsonlint.com/>, <http://codebeautify.org/jsonvalidate>, etc.

**Comment by edlisten** [comment]
The JSON file appears to be working:  And we did get colorblind setting to
work.

{ "adminSettings": { "Value": "{ \"netWhitelist\":
\"about-scheme\nbehind-the-scene\nchrome-extension-scheme\nchrome-scheme\nloopconversation.about-scheme\nopera-scheme\nforbes.com\nespn.go.com\"
}" } }


*Bjorn Behrendt M.Ed ~ Never Stop Learning*
*   bj@edlisten.com <bj@edlisten.com> | **Blog: *Edlisten.com
<http://edlisten.com/>

**Comment by gorhill** [comment]
Probably the `\n` in the inner JSON should be `\\n`. Double-encoding a JSON string is tricky.

**Comment by guygg** [comment]
Just stumbled upon this thread while implementing policy settings to start pushing out uBlock to replace ABP across all our Chromebooks. With a little fiddling, was able to push multiple settings and the netWhitelist with multiple domains. One question, though, is if there's a way to push out whitelist domains that doesn't replace the user's whitelist settings? When I push out a couple domains via the netWhitelist value, it replaces the entire list rather than appending/updating existing ones. For anybody else's benefit, here's the JSON I'm using in testing that has a couple user settings as well as a couple example whitelist domains:

{ "adminSettings": { "Value": "{ \"userSettings\": {\"colorBlindFriendly\": true, \"cloudStorageEnabled\": true }, \"netWhitelist\": \"hellointernet.fm\\nwikipedia.com\" }" } }

**Comment by gorhill** [comment]
> One question, though, is if there's a way to push out whitelist domains that doesn't replace the user's whitelist settings?

Not possible, support for this would need to be added.

**Comment by guygg** [comment]
Gotcha. Well, then, I look towards the coding heavens with the cutest of imploring eyes. :)

**Comment by abhiWA** [comment]
Please help. I have a different case, because I have deployed uBlock Origin on Chrome using gpo. This extension is deployed using ExtensionInstallForcelist under Google Chrome adm gpo settings. So, I do not have the same path under registry. I have Google > Chrome > ExtensionInstallForceList. Now, it does not give me sub-key for my extension.

Now, I need to setup a custom whitelist. I am not sure, where I create this registry string. Please see below:
![reg path chrome](https://cloud.githubusercontent.com/assets/22547638/18998802/2dbbc872-8708-11e6-85ec-93c9a4c32195.png)

In my registry, I have Chrome > ExtensionInstallForcelist. I am not sure where do I create my string adminSettings. I have tried creating it under ExtensionInstallForcelist, also tried creating a child key called policy. Any suggestion would be appreciated. 

**Following is the value being used:**

{ "adminSettings": { "Value": "{ \"netWhitelist\": \"about-scheme\\nbehind-the-scene\\nchrome-extension-scheme\\nchrome-scheme\\nloopconversation.about-scheme\\nopera-scheme\\npastebin.com\\mydomain.com\" }" } }

**Comment by benwa** [comment]
Hi @abhiWA, to do it via Group Policy, you'll make a Group Policy Preference of `adminSettings` as a `REG_SZ` under `Software\Policies\Google\Chrome\3rdparty\extensions\cjpalhdlnbpafiamejdnhcphjbkeiagm\policy`
![image](https://cloud.githubusercontent.com/assets/1351571/18998992/1dc02642-8709-11e6-8c72-be98322f5720.png)

My settings look like:
```json
{"userSettings":{"autoUpdate":true,"contextMenuEnabled":false,"showIconBadge":false},"netWhitelist":"about-scheme\nbehind-the-scene\nchrome-extension-scheme\nchrome-scheme\nlocalhost\nlogmein.com\nloopconversation.about-scheme\nopera-scheme"}
```

**Comment by abhiWA** [comment]
Hello @benwa,

Thank You so much for your quick response. I apologise, but I guess I am still not certain on what to do. I want to push this whitelist settings for uBlock Origin. I have deployed it as a computer policy to an OU. Now, do I edit the current GPO and go to Computer Config > Preferences > Windows Settings and create a new registry key here. 

I tried going to my PC where the extension is deployed by GPO and it does not give me the same path in my regedit. I get Software > Policy > Google > Chrome > ExtensionInstallForcelist. This is it, I do not get 3rdparty\extensions\cjpalhdlnbpafiamejdnhcphjbkeiagm\policy. Please see below:
![image](https://cloud.githubusercontent.com/assets/22547638/18999332/086b243e-870b-11e6-8052-608d6786edd2.png)

Even the extension is a value since I pushed it using adm templates of Chrome. 
I would appreciate your assistance on this.

**Comment by benwa** [comment]
You have to type in the path manually, it will create the correct entries for you.
Once that's done and you've done a `gpupdate` on the client computer, open `chrome://policy/` and click *Reload policies*.

**Comment by abhiWA** [comment]
Hello @benwa 

Thanks so much for following back on this one. 

GOT IT! YOU ARE GENIUS. Now, let me test if it works :P

**Comment by abhiWA** [comment]
Hello @benwa,

I guess this worked halfway. I can see my domains in the policy, see below:
![image](https://cloud.githubusercontent.com/assets/22547638/18999964/120feea4-870e-11e6-969a-ba1a312cf456.png)

This does not seem to update the filters for uBlock tho, see below:
![image](https://cloud.githubusercontent.com/assets/22547638/18999980/26693d92-870e-11e6-8c4d-286cb5a28092.png)

So, this worked for chrome policy, but it is not updating uBlock Origin. Any idea?

Thanks again

**Comment by benwa** [comment]
You must either disable and reenable the extension, or restart the browser completely.

**Comment by abhiWA** [comment]
Hey @benwa 

Tried restarting the computer, uBlock, Chrome; still does not work. Policy shoes the update, but not the extension itself.

**Comment by benwa** [comment]
Hmm, then I'd say the json isn't valid.  Run it through a validator and then minify it.

**Comment by abhiWA** [comment]
Tried that, still no lead  @benwa  :/

**Comment by gorhill** [comment]
> Following is the value being used:
> 
>     { "adminSettings": { "Value": "{ \"netWhitelist\": \"about-scheme\nbehind-the-scene\nchrome-extension-scheme\nchrome-scheme\nloopconversation.about-scheme\nopera-scheme\npastebin.com\mydomain.com\" }" } }

It's not properly JSON-encoded. It should be:

    { "netWhitelist": "about-scheme\nbehind-the-scene\nloopconversation.about-scheme\nopera-scheme\nvivaldi-scheme" }

**Comment by gorhill** [comment]
Here, I just wrote a quick-and-dirty helper to convert to/from `adminSettings`: <http://raymondhill.net/ublock/adminSetting.html>.

**Comment by abhiWA** [comment]
@gorhill Thanks a lot for your response. 

I used your tool and it gave me the following:

"{ \"adminSettings\": { \"Value\": \"{ \\\"netWhitelist\\\": \\\"about-scheme\\\\nbehind-the-scene\\\\nchrome-extension-scheme\\\\nchrome-scheme\\\\nloopconversation.about-scheme\\\\nopera-scheme\\\\npastebin.com\\\\nhotjar.com\\\\nnewrelic.com\\\\nmxpnl.com\\\" }\" } }"

I inserted the following and got above:

{ "adminSettings": { "Value": "{ \"netWhitelist\": \"about-scheme\\nbehind-the-scene\\nchrome-extension-scheme\\nchrome-scheme\\nloopconversation.about-scheme\\nopera-scheme\\npastebin.com\\nhotjar.com\\nnewrelic.com\\nmxpnl.com\" }" } }

Still does not work for me

**Comment by gorhill** [comment]
> I used your tool and it gave me the following:

You did not follow the instruction correctly. It says: "Content of the back-up file used for `adminSettings`".

You entered `{ "adminSettings": { "Value": "{ \"net ...`: there is no setting called `adminSettings` in uBO's back-up file.

**Comment by abhiWA** [comment]
Hello @gorhill ,

Thank you so much for your assistance. Got it working in the uBlocker Origin Whitelist, finally. Phew :D 
Thanks so much @gorhill and @benwa, but its a big bummer because Whitelist does not work :( 

Only filter works, for some reason whitelist is not working in my case and I have to put filter. Can filters be configured as well using gpo? Do you have syntax for that?

**Comment by gorhill** [comment]
> Can filters be configured as well using gpo?

You could create your own filter list, save it to your server from which it can be pulled by other users (could even be a private gist on GitHub), and subscribe everybody to it using custom filter list.

Example:

    {
      "userSettings": {
        "externalLists": "https://gist.githubusercontent.com/gorhill/ef1b62d606473c68d524/raw/f8181faac18cb5172c7c9bca8e5a3b22f0c925d0/gistfile1.txt\n"
      }
    }

Become:

    "{\n  \"userSettings\": {\n    \"externalLists\": \"https://gist.githubusercontent.com/gorhill/ef1b62d606473c68d524/raw/f8181faac18cb5172c7c9bca8e5a3b22f0c925d0/gistfile1.txt\\n\"\n  }\n}"

**Comment by fellon** [comment]
Another admin and I have been banging our heads against this most of the morning. Here is the last strings we have tried. (Chromebooks only)

{ "adminSettings": { "Value": "{ \"netWhitelist\": \"about-scheme\\nbehind-the-scene\\nchrome-extension-scheme\\nchrome-scheme\\nclever.com\\nfilepicker.com\\nfilepicker.io\\nloopconversation.about-scheme\\nopera-scheme\\ns3.amazonaws.com\" }" } }

We also have tried the same string minus the adminSettings value. 

No matter what format we upload, it does not show in the Chrome://policy.  Just does not want to stick. I know we are doing something wrong here. Suggestions?

**Comment by gorhill** [comment]
> Here is the last strings we have tried.

Bad encoding. Just use the tool I have posted above, that removes any guessing. Here is the string value to use for "adminSettings":

    "{ \"netWhitelist\": \"about-scheme\\nbehind-the-scene\\nchrome-extension-scheme\\nchrome-scheme\\nclever.com\\nfilepicker.com\\nfilepicker.io\\nloopconversation.about-scheme\\nopera-scheme\\ns3.amazonaws.com\" }"

**Comment by JPT62089** [comment]
I'm currently trying to disable the EasyPrivacy list as it messes with sites functionality than it's worth for us. I'm sadly not exceeding in this. The colorBlindFriendly option works, but not the filterLists. Do I need to list out everything in filterLists rather than just what I wish to turn off?

`{"userSettings":{"autoUpdate":true,"colorBlindFriendly":true,"filterLists":{"assets/thirdparties/easylist-downloads.adblockplus.org/easyprivacy.txt":{"off":true}}}}`

**Comment by gorhill** [comment]
Please use the [encoder tool](http://raymondhill.net/ublock/adminSetting.html) to avoid mistake. Your string is not correct, the `filterLists` property is not a member of the `userSettings` property, you removed too many curly brackets.

Try:

    {"filterLists":{"assets/ublock/experimental.txt":{"off":true},"assets/thirdparties/easylist-downloads.adblockplus.org/easyprivacy.txt":{"off":true}}}

**Comment by JPT62089** [comment]
Ha! I did not see that tool! Thank you, @gorhill! Much appreciated. Unsurprisingly, it works now :D

**Comment by NoSubstitute** [comment]
Sorry for maybe asking in the wrong place, but is there some guide anywhere how to export the settings and then push them to users? I don't want to whitelist anything (right now), but I do want to enable Dan Pollock's host file for everyone. I found where to export settings from one browser, but do I really need to push all that? Isn't it enough to push the diff from the default settings?

**Comment by gorhill** [comment]
> how to export the settings and then push them to users?

On top of the existing settings or to replace the existing settings?

**Comment by NoSubstitute** [comment]
Since this will be for people who have never before used it, the primary
objective would be replace.

If it has to be done again, some time in the future, I think I still feel
replace would be the proper approach. Don't you?

**Comment by gorhill** [comment]
Entries in `adminSettings` will replace current settings, but every time the extension starts -- is this what you need?

**Comment by benwa** [comment]
Personally, I prefer the approach of if it's not defined in the policy, use defaults or user settings.  That follows in line with Chrome's (and Group Policy-like systems) methods.

**Comment by gorhill** [comment]
There is this: <https://github.com/gorhill/uBlock/wiki/Deploying-uBlock-Origin>.

With 1.11.0, selecting filter lists will be much more simple -- it will be the `selectedFilterLists` array entry in the backup file.

**Comment by KTac** [comment]
Can someone help me please. I'm losing my mind trying to get this working on Windows. I am not using Group Policy and I do not currently have the Chrome administrative template installed. I'm unclear if this is required but I wouldn't think so. This is for a local machine that will be accessed by many users. I have manually set the necessary registry entries like so.

![image](https://cloud.githubusercontent.com/assets/7475912/23000697/9d013230-f3af-11e6-8d96-ea29c3e94d7a.png)

![image](https://cloud.githubusercontent.com/assets/7475912/23000579/2bbce97a-f3af-11e6-8c3e-9fefc16a35d8.png)

The extension installs automatically just fine but for my life I can't get the policy to take effect. I tried a much more detailed set of settings at first but after I couldn't get those to work I decided to just try one non-default setting which is what you see above.

The string I used for adminSettings is:
`{"userSettings":{"colorBlindFriendly":false}}`

I ran the original code through a JSON validator and then ran it through @gorhill's encoder tool to get it to a single line, so I'm pretty sure the formatting of the string is not the problem. What am I missing?

**Comment by gorhill** [comment]
> The string I used for adminSettings is:
> `{"userSettings":{"colorBlindFriendly":false}}`

The default value for `colorBlindFriendly` is `false`, so your `adminSettings` won't change anything.

**Comment by KTac** [comment]
Wow, I can't believe I did that. I changed the value to true and still nothing. Either way, shouldn't the fact that the extension is installed and the properly formatted registry value exists cause the policy to show up as enabled under chrome://policy?

**Comment by gorhill** [comment]
Yes, it should show in `chrome://policy`. I am not in a position to help here, I do not have Windows and can't test stuff. According to [this comment above](https://github.com/gorhill/uBlock/issues/832#issuecomment-250789906), I can't see anything wrong in your screenshot.

**Comment by gorhill** [comment]
Actually, the user who succeeded in making it work is using `HKEY_CURRENT_USER` while I see you are using `HKEY_LOCAL_MACHINE`.

**Comment by NoSubstitute** [comment]
I think he's using HKEY_LOCAL_MACHINE because he wants the policy to run
for all local users.

**Comment by pcurb23** [comment]
Thank you so much for implementing this for us poor overworked security conscious admins.  It worked flawlessly on the first try after following the writeup @ https://github.com/gorhill/uBlock/wiki/Deploying-uBlock-Origin
We deployed a reg key to HKLM and used the handy tool [here](http://raymondhill.net/ublock/adminSetting.html) to convert the string to JSON.

**Comment by najamss** [comment]
Hi @benwa,

I know, it's an old post but do you know how can I do the same for Privacy Badger, what you suggested for UBlock Origin via GPO?

**Comment by benwa** [comment]
@najamss With a quick look at `chrome://policy`, it doesn't seem like Privacy Badger supports policies.  If you want them to, I'd file an issue [here](https://github.com/EFForg/privacybadger/issues).  If you need to implement now, I'm fairly certain uBlock Origin will accomplish the same thing.

**Comment by najamss** [comment]
@benwa 

Thanks a heap for looking in to it. In fact, we have deployed both Privacy Badger and UBlock Origin. They both are blocking AddThis share buttons on our websites; therefore, I wanted to add our required domains to their whitelist domains

**Comment by joavaran** [comment]
@gorhill: How would you do the same adminsettings for MACos with plist? Is there a converter I can use?
So in ublock backutp to file and use a converter? or use a reg -> plist converter?

**Comment by Alcon835** [comment]
First: this thread has been a HUGE help! I still have an issue related to this:

If I "pause" uBlock Origin on a page and then reset chrome, the policy settings will overwrite whatever pages I've paused. If I don't have the adminSettings registry item, it won't overwrite the pages I've paused. 

Is this expected behavior and is there a work around that allows me to push the whitelist to all computers without overwriting a user's personal pause/white list?

**Comment by kingio** [comment]
I did the same as @KTac second screen on W10 Home Edition and didn't work. I don't know why nobody is sharing a reg file to make things easier, so i'm sharing the one that i'm doing:
ublock.reg

```
Windows Registry Editor Version 5.00

[HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Google\Chrome\3rdparty\extensions\cjpalhdlnbpafiamejdnhcphjbkeiagm\policy]
"adminSettings"="{\"userSettings\":{\"colorBlindFriendly\":true}}"
```

**Comment by miruser** [comment]
hey kingio

it is very easy. use ublock backup to file function with the settings you want to have.
then use http://raymondhill.net/ublock/adminSetting.html + JSON-encoded settings to be used for adminSettings as a plain string value. Voila... Took me weeks to find this out! Have fun

**Comment by kingio** [comment]
@miruser i already did that without success. Could you please export your `adminSettings` from registry and share it? By selecting the key and then clicking on File -> Export you will have the .reg file that can be opened with notepad itself.

**Comment by miruser** [comment]
hey kingio.. 

Windows Registry Editor Version 5.00

[HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Google\Chrome\3rdparty\extensions\cjpalhdlnbpafiamejdnhcphjbkeiagm\policy]
"adminSettings"="{\"timeStamp\":1507099983095,\"version\":\"1.14.8\",\"userSettings\":{\"advancedUserEnabled\":false,\"alwaysDetachLogger\":false,\"autoUpdate\":true,\"cloudStorageEnabled\":false,\"collapseBlocked\":true,\"colorBlindFriendly\":true,\"contextMenuEnabled\":true,\"dynamicFilteringEnabled\":false,\"externalLists\":\"\",\"firewallPaneMinimized\":true,\"hyperlinkAuditingDisabled\":true,\"ignoreGenericCosmeticFilters\":false,\"largeMediaSize\":50,\"parseAllABPHideFilters\":true,\"prefetchingDisabled\":true,\"requestLogMaxEntries\":1000,\"showIconBadge\":true,\"tooltipsDisabled\":false,\"webrtcIPAddressHidden\":false},\"selectedFilterLists\":[\"plowe-0\",\"malware-1\",\"malware-0\",\"easyprivacy\",\"easylist\",\"ublock-unbreak\",\"ublock-privacy\",\"ublock-badware\",\"ublock-filters\",\"user-filters\"],\"hiddenSettingsString\":\"assetFetchTimeout 30\\nautoUpdateAssetFetchPeriod 120\\nautoUpdatePeriod 1\\nignoreRedirectFilters false\\nignoreScriptInjectFilters false\\nmanualUpdateAssetFetchPeriod 2000\\npopupFontSize unset\\nsuspendTabsUntilReady false\\nuserResourcesLocation unset\",\"netWhitelist\":\"\",\"dynamicFilteringString\":\"behind-the-scene * 3p-frame noop\\nbehind-the-scene * 3p noop\",\"urlFilteringString\":\"\",\"hostnameSwitchesString\":\"\",\"userFilters\":\"\",\"filterLists\":{\"assets/thirdparties/pgl.yoyo.org/as/serverlist\":{\"off\":false},\"assets/thirdparties/mirror1.malwaredomains.com/files/justdomains\":{\"off\":false},\"assets/thirdparties/www.malwaredomainlist.com/hostslist/hosts.txt\":{\"off\":false},\"assets/thirdparties/easylist-downloads.adblockplus.org/easyprivacy.txt\":{\"off\":false},\"assets/thirdparties/easylist-downloads.adblockplus.org/easylist.txt\":{\"off\":false},\"assets/ublock/unbreak.txt\":{\"off\":false},\"assets/ublock/privacy.txt\":{\"off\":false},\"assets/ublock/badware.txt\":{\"off\":false},\"assets/ublock/filters.txt\":{\"off\":false},\"assets/user/filters.txt\":{\"off\":false},\"assets/ublock/experimental.txt\":{\"off\":true}}}"

**Comment by mcgituser** [comment]
hey gorhill,

Thanks for all the hard work and info here.  I was wondering if you've had a chance to work on merging the user's setting and the adminSettings?

We are looking to push an initial set of sites for whitelisting and then let the users add to it as they please going forward.  Can you think of a good what to do that?  I was thinking perhaps if there was a local configuration file that we can modify and push out during the deployment that contains a set of predefined whitelists and can be added to the users, that would work.  Let me know your thoughts.

Thanks again

**Comment by jhavens12** [comment]
I've read all these comments and am still having issues uploading a simple whitelist to GAFE for my users. This is the string I'm trying to use:


`"{ \"netWhitelist\": \"https://www.pbisassessment.org\" }"`

Am I missing something here?

**Comment by logan-19** [comment]
I've read all these comments and am still having issues.
Firefox 52.0.2 + uBO 1.17.4 

uBO does not accept the settings that are advised in the comments.
Please let me know what settings are needed?

**Comment by Bangaio65** [comment]
On Chromium Edge, the registry location is:
`HKEY_CURRENT_USER\Software\Policies\Microsoft\Edge\3rdparty\extensions\odfafepnkmbhccpbejgmiehpchacaeak\policy`
(It seems to get ignored if set in HKLM)

Now a question: is there a way to have the settings stored in a file like in Firefox? So I could point to that file (stored in the network) and not have to edit settings in two places in case I want to change a setting.
