### ISSUE TITLE
[Palemoon] Button disappears after restart

### ISSUE THREAD

**Issue by Tharn** [gorhill/uBlock#833]
Hi,

There is a thread on the Palemoon forum (http://forum.palemoon.org/viewtopic.php?f=15&t=9599) discussing this issue. A number of users report that the uBlock button will disappear after a restart.

**Comment by gorhill** [comment]
I can't reproduce this, but I could try to shuffle a bit of code around -- related to the creation of the toolbar icon, and those who can reproduce it could see if this helps.

**Comment by gorhill** [comment]
1.3.0rc2 is ready (also on dev channel on AMO), so it would be nice for those with the issue to verify whether this helps.

**Comment by elsy04** [comment]
I noted this issue since some weeks ago, it is weird, but the button will indeed disappear after some browser restarts. I found a kind of workaround that still works here, and it was placing it in other window's location (lower right), than the original upper right one.

**Comment by LimboSlam** [comment]
Been testing this, but I have not experience any disappearance of Ublock. Though, I will say at time this does happened, but frequently, no.

**Comment by gorhill** [comment]
[Looks like this did not help](http://forum.palemoon.org/viewtopic.php?f=15&t=9599#p67729):

> I installed uBlock Origin 1.3.0rc2 and the problem still exists with PM 25.7.2 x86.
> Strangly enough, I have a laptop with PM 25.7.1 x86 and uBlock Origin v1.1.1 and the problem does not occur.

**Comment by gorhill** [comment]
I pushed a new "rc4" build with a tentative fix for the toolbar button issues. Would be nice if this could be tried by those who are able to reproduce the issue. I won't push this to developer channel on AMO unless it is well confirm it fixes the issue -- so this will have to be grabbed from here (which means `rc4` won't appear in the version number).

**Comment by Tharn** [comment]
Thanks, I put up a link with the new build.

**Comment by gorhill** [comment]
I added another chunk of code to further defer adding the toolbar icon at a later time if uBlock can't find the required component when a new window is created. Hopefully this may take care of the case of this user reporting that the toolbar icon fails to be added when a new window is opened. It's in a new rc4 build.

**Comment by gorhill** [comment]
Reportedly, this is finally fixed with 567b1007f8fba00776ebc8d6dfce76480251cf60.

**Comment by Zement** [comment]
Hello, I'm still having this problem. The uBlock (1.3.6) icon disappears after a browser (Palemoon v25.8.1 x64) restart. On Windows 7 x64.
The icon is currently placed in the statusbar, but placing it into any other bar unfortunately doesn't solve the problem for me.

**Comment by TPS** [comment]
@gorhill @wolfbeast @Zement I'm currently having this issue with https://github.com/gorhill/uBlock/releases/tag/1.6.2b0 on https://github.com/MoonchildProductions/Pale-Moon/releases/tag/26.1.0_Release (x64) on Windows 10.…  Does anyone else? What other info can I provide?

**Comment by gorhill** [comment]
Is the button in the _Customize_ dialog?
![a](https://cloud.githubusercontent.com/assets/585534/13144931/7ab8e400-d61b-11e5-9834-5a330b17fad4.png)

**Comment by TPS** [comment]
Yes, I take it from there, & put it in statusbar every startup, but it's disappeared on next startup.

**Comment by gorhill** [comment]
I remember such issue raised in the past. I investigated this in the past and I vaguely remember there was something peculiar in the way Ghostery was inserting its own icon in the toolbar.

**Comment by TPS** [comment]
Oddly, though, it's the _only_ icon (that I have or found) that's obliterated by Ghostery.  Since both are restartless, you can enable uBlock, verifying that the icon is on the statusbar, then enable Ghostery, just to watch the uBlock icon evaporate.  It's quite frustrating.…

**Comment by gorhill** [comment]
> Is it useful under Pale Moon?

No, the legacy toolbar button is always used on Pale Moon. The purpose of the setting is to force the use of legacy toolbar button on Firefox Australis.

**Comment by 3NQfgBiMnL** [comment]
I think this is happening to me too. Pale Moon 27.3.0 64 bit + uBlock Origin 1.12.4. Every once in a while the button disappears from the Navigation Toolbar and I have to add it back from the Customize dialog.

**Comment by gorhill** [comment]
@3NQfgBiMnL When you launch Pale Moon, does it take long before it's up and ready?

**Comment by 3NQfgBiMnL** [comment]
It seems to launch fairly fast to me.

I tried various multiple actions related to uBlock the other day to try and reproduce the issue but couldn't get it to deliberately happen. :/
